object LanguageUtil {
    val androidXmlMappings = arrayOf(
        NlsMap("en", "en", "English"),
        NlsMap("en_us", "en-rUS", "American English"),
        NlsMap("en_us", "en-rU1", "American English"),
        NlsMap("ar", "ar", "Arabic"),
        NlsMap("cs", "cs", "Czech"),
        NlsMap("de", "de", "German"),
        NlsMap("el", "el", "Greek"),
        NlsMap("es", "es", "Spanish"),
        NlsMap("es_mx", "es-rMX", "Mexican Spanish"),
        NlsMap("fr", "fr", "French"),
        NlsMap("fr_ca", "fr-rCA", "Canadian French"),
        NlsMap("in", "in", "Indonesian"),
        NlsMap("iw", "iw", "Hebrew"),
        NlsMap("ja", "ja", "Japanese"),
        NlsMap("kk", "kk", "Kazakh"),
        NlsMap("ko", "ko", "Korean"),
        NlsMap("pl", "pl", "Polish"),
        NlsMap("pt", "pt", "Portuguese"),
        NlsMap("ru", "ru", "Russian"),
        NlsMap("sk", "sk", "Slovak"),
        NlsMap("tr", "tr", "Turkish"),
        NlsMap("vi", "vi", "Vietnamese"),
        NlsMap("zh", "zh", "Simplified Chinese"),
        NlsMap("zh", "zh-rCN", "Simplified Chinese"),
        NlsMap("zh_tw", "zh-rHK", "Traditional Chinese"),
        NlsMap("zh_tw", "zh-rTW", "Traditional Chinese")
    )

    val iosJsonMappings = arrayOf(
        NlsMap("en", "en", "English"),
        NlsMap("en_us", "en_u1", "American English"),
        NlsMap("ar", "ar", "Arabic"),
        NlsMap("cs", "cs", "Czech"),
        NlsMap("de", "de", "German"),
        NlsMap("el", "el", "Greek"),
        NlsMap("es", "es", "Spanish"),
        NlsMap("es_mx", "es_MX", "Mexican Spanish"),
        NlsMap("fr", "fr", "French"),
        NlsMap("fr_ca", "fr_CA", "Canadian French"),
        NlsMap("HASE_en", "HASE_en", "HASE English"),
        NlsMap("HASE_zh", "HASE_zh", "HASE Chinese"),
        NlsMap("HASE_zh_tw", "HASE_zh_tw", "HASE Traditional Chinese"),
        NlsMap("in", "in", "Indonesian"),
        NlsMap("iw", "iw", "Hebrew"),
        NlsMap("ja", "ja", "Japanese"),
        NlsMap("kk", "kk", "Kazakh"),
        NlsMap("ko", "ko", "Korean"),
        NlsMap("pl", "pl", "Polish"),
        NlsMap("pt", "pt", "Portuguese"),
        NlsMap("ru", "ru", "Russian"),
        NlsMap("sk", "sk", "Slovak"),
        NlsMap("tr", "tr", "Turkish"),
        NlsMap("vi", "vi", "Vietnamese"),
        NlsMap("zh", "zh", "Simplified Chinese"),
        NlsMap("zh_tw", "zh_tw", "Traditional Chinese")
    )
    val cpJsonMappings = arrayOf(
        NlsMap("en", "en", "English"),
        NlsMap("en_us", "en_us", "American English"),
        NlsMap("ar", "ar", "Arabic"),
        NlsMap("cs", "cs", "Czech"),
        NlsMap("de", "de", "German"),
        NlsMap("el", "el", "Greek"),
        NlsMap("es", "es", "Spanish"),
        NlsMap("es_mx", "es_mx", "Mexican Spanish"),
        NlsMap("fr", "fr", "French"),
        NlsMap("fr_ca", "fr_ca", "Canadian French"),
        NlsMap("HASE_en", "HASE_en", "HASE English"),
        NlsMap("HASE_zh", "HASE_zh", "HASE Chinese"),
        NlsMap("HASE_zh_tw", "HASE_zh_tw", "HASE Traditional Chinese"),
        NlsMap("in", "in", "Indonesian"),
        NlsMap("iw", "iw", "Hebrew"),
        NlsMap("ja", "ja", "Japanese"),
        NlsMap("kk", "kk", "Kazakh"),
        NlsMap("ko", "ko", "Korean"),
        NlsMap("pl", "pl", "Polish"),
        NlsMap("pt", "pt", "Portuguese"),
        NlsMap("ru", "ru", "Russian"),
        NlsMap("sk", "sk", "Slovak"),
        NlsMap("tr", "tr", "Turkish"),
        NlsMap("vi", "vi", "Vietnamese"),
        NlsMap("zh", "zh", "Simplified Chinese"),
        NlsMap("zh_tw", "zh_tw", "Traditional Chinese")
    )

}

data class NlsMap(val oCode: String, val outputCode: String, val remark: String)